$configs = $HOME/.config/hypr/configs

source= $configs/wallpaper.conf

source= $configs/01-UserDefaults.conf

source= $configs/Startup_Apps.conf

source= $configs/ENVariables.conf

source= $configs/UserDecorations.conf

source= $configs/UserAnimations.conf

source= $configs/keybind.conf

source= $configs/UserSettings.conf


# nwg-displays
source= $configs/monitors.conf
