source = $HOME/.config/hypr/colors.conf

background {
    monitor = 
    path = $HOME/.config/hypr/wallpaper/wallpaper.jpg
    blur_size = 8
    blur_passes = 3
    brightness = 0.95
}

# --- TEKS PASSWORD ---
label {
    monitor =
    text = Password
    font_size = 18
    position = 0, -180
    halign = center
    valign = center
}

# --- INPUT PASSWORD ---
input-field {
    monitor =
    size = 270, 55
    outline_thickness = 2
    placeholder_text =
    fade_on_empty = false
    rounding = 10
    position = 0, -230

    outer_color = $charcoal_grey
    inner_color = $fog_grey
    font_color = rgba(255,255,255,1)
    dots_center = true
    text_align = center
}

# --- JAM ---
label {
    monitor =
    text = $TIME
    font_size = 60
    position = 0, 230
    halign = center
    valign = center
}


